/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.2-28-g3cb1f4b2bc"
#endif /* AVUTIL_FFVERSION_H */
